# Generated by Django 3.2 on 2021-04-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='ddd',
            field=models.CharField(default='0000000', max_length=60),
        ),
    ]
