# Generated by Django 3.2 on 2021-04-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_supplies_ddd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='description',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
