# Generated by Django 3.2 on 2021-04-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supplies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='description',
            field=models.CharField(error_messages={'unique': 'This email has already been registered.'}, max_length=60, unique=True),
        ),
    ]
