# Generated by Django 3.2 on 2021-04-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_supplies_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('email', models.EmailField(error_messages={'unique': 'El chofer ya ha sido  registrado con anterioridad.'}, max_length=254, unique=True)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='supplies',
            name='description',
            field=models.CharField(error_messages={'unique': 'El insumo ya ha sido registrado con anterioridad.'}, max_length=60, unique=True),
        ),
    ]
