# Generated by Django 3.2 on 2021-04-24 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210424_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(error_messages={'unique': 'El vehículo ya ha sido  registrado con anterioridad.'}, max_length=5, unique=True)),
                ('model', models.CharField(max_length=30)),
                ('licencePlate', models.CharField(max_length=7)),
                ('seatNumbers', models.IntegerField()),
                ('type', models.CharField(max_length=15)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.driver')),
            ],
        ),
    ]
