# Generated by Django 3.2 on 2021-04-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='full_name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
