# Generated by Django 3.2 on 2021-04-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_driver_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='full_name',
            new_name='fullName',
        ),
    ]
