# Generated by Django 3.2 on 2021-04-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.IntegerField(error_messages={'unique': 'La ruta ya ha sido registrado con anterioridad.'}, max_length=5, unique=True)),
                ('origin', models.CharField(max_length=50)),
                ('destiny', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.bus')),
            ],
        ),
    ]
