# Generated by Django 3.2 on 2021-04-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
