# Generated by Django 3.2 on 2021-04-27 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destino', to='api.place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='identification',
            field=models.IntegerField(error_messages={'unique': 'La ruta ya ha sido registrado con anterioridad.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origen', to='api.place'),
        ),
    ]
