# Generated by Django 3.2 on 2021-04-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210427_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='identification',
        ),
    ]
