# Generated by Django 3.2 on 2021-04-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_place_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplies',
            name='ddd',
        ),
        migrations.AddField(
            model_name='supplies',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
