# Generated by Django 3.2 on 2021-04-30 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210427_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='identification',
        ),
        migrations.AddField(
            model_name='route',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='destiny',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='destino', to='api.place'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='origen', to='api.place'),
        ),
    ]
