# Generated by Django 3.2 on 2021-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210430_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
