# Generated by Django 3.2 on 2021-05-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_driver_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
