# Generated by Django 3.2 on 2021-05-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bus_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('C', 'Cómoda'), ('SC', 'Super-Cómoda')], max_length=15),
        ),
    ]
