# Generated by Django 3.2 on 2021-05-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_bus_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='type',
            field=models.CharField(choices=[('C', 'Cómoda'), ('SC', 'Super-Cómoda')], max_length=2),
        ),
    ]
