# Generated by Django 3.2 on 2021-05-02 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_bus_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destiny',
            new_name='destination',
        ),
    ]
